services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.geode
    container_name: geode
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - DB_URL=postgres://postgres:postgres@postgres:5432/geo
      - LISTEN_ADDR=0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge